baseurl: /
languageCode: en-us
title: xiaodong
theme: "hugo-ivy"
googleAnalytics: ""
disqusShortname: "xiaodong_feng"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
hasCJKLanguage: true
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩
rssLimit: 100


permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "日志"
      url: "/cn/"
      weight: 4
    - name: "Recipe"
      url: "/recipe/"
      weight: 5
    - name: "Tips"
      url: "/tips/"
      weight: 6 
    - name: "Vitae"
      url: "/vitae/"
      weight: 7

















params:
  description: "Xiaodong Feng"
  footer: "&copy; [Xiaodong](https://fxd.name) 2021 | [Github](https://github.com/xiaodfeng)"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"
  highlightjsVersion: "9.12.0"
  disqusURL: "https://fengxiaodong.com"
  customJS:
    - "js/fix-toc.js"
    - "js/center-img.js"
    - "js/right-quote.js"
    - "js/no-highlight.js"
    - "js/fix-footnote.js"
    - "js/math-code.js"
    - "js/external-link.js"
    - "js/alt-title.js"
    - "js/header-link.js"
  author:
    en: "Xiaodong Feng"
    cn: "冯晓东"
    
  
blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

  

markup:
  goldmark:
    renderer:
      unsafe: true
      



