baseurl: /
languageCode: en-us
title: xiaodong
theme: "hugo-ivy"
googleAnalytics: ""
disqusShortname: "xiaodong_feng"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
hasCJKLanguage: true
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩
rssLimit: 100


permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 4
    - name: "R"
      url: "/en/r/"
      weight: 5 
    - name: "关于"
      url: "/cn/about/"
      weight: 6
    - name: "简历"
      url: "/cn/vitae/"
      weight: 7
    - name: "日志"
      url: "/cn/"
      weight: 8
    - name: "菜谱"
      url: "/cn/recipe/"
      weight: 9













params:
  description: "Xiaodong Feng"
  footer: "&copy; [Jinji](https://jinjipang.com) 2021 | [Github](https://github.com/JinjiPang) | [Twitter](https://twitter.com/PangKimki)"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"
  highlightjsVersion: "9.12.0"
  disqusURL: "https://jinjipang.com"
  customJS:
    - "js/fix-toc.js"
    - "js/center-img.js"
    - "js/right-quote.js"
    - "js/no-highlight.js"
    - "js/fix-footnote.js"
    - "js/math-code.js"
    - "js/external-link.js"
    - "js/alt-title.js"
    - "js/header-link.js"
  author:
    en: "Kimki"
    cn: "金吉"
  
  
blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

  

markup:
  goldmark:
    renderer:
      unsafe: true
      



