baseurl: "https://fxd.name/"
languageCode: "en-us"
title: "Xiaodong Feng"
theme: "hugo-ivy"
disqusShortname: "xiaodong"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
hasCJKLanguage: true

enableEmoji: true

preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩
rssLimit: 100

permalinks:
  cn: "/:sections/:year/:month/:slug/"
  en: "/:sections/:year/:month/:slug/"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "日志"
      url: "/cn/"
      weight: 4
    - name: "Recipe"
      url: "/recipe/"
      weight: 5
    - name: "Tips"
      url: "/tips/"
      weight: 6 
    - name: "Vitae"
      url: "/vitae/"
      weight: 7



params:
  description: "Xiaodong Feng"
  footer: "&copy; [Xiaodong](https://fxd.name) 2021 | [Github](https://github.com/xiaodfeng)"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"
  highlightjsVersion: "9.12.0"
  disqusURL: "https://fengxiaodong.com"
  author:
   en: "Xiaodong Feng"
   cn: "冯晓东"  

  customJS:

    - "fix-toc.js"
    - "center-img.js"
    - "right-quote.js"
    - "no-highlight.js"
    - "fix-footnote.js"
    - "math-code.js"
    - "external-link.js"
    - "alt-title.js"
    - "header-link.js"



blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

  

markup:
  goldmark:
    renderer:
      unsafe: true
      



